/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;

/**
 *
 * @author MY PC
 */
public class CariSuratGUI extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public CariSuratGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        spJuz = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jListCariSurat = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        tfNamaSurat = new javax.swing.JTextField();
        labelNama = new javax.swing.JLabel();
        labelJudul = new javax.swing.JLabel();
        labelKategori = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        btnBack.setForeground(new java.awt.Color(80, 148, 101));
        btnBack.setText("Kembali");
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 90, 40));

        btnPlay.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(51, 51, 255));
        btnPlay.setText("Play");
        jPanel2.add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 90, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jListCariSurat.setOpaque(false);
        jPanel1.add(jListCariSurat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 1240));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/2.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 350, 620));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 620));

        spJuz.setViewportView(jPanel1);

        jPanel2.add(spJuz, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 370, 310));

        btnCari.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnCari.setForeground(new java.awt.Color(80, 148, 101));
        btnCari.setText("Cari");
        jPanel2.add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 80, 30));
        jPanel2.add(tfNamaSurat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 270, 30));

        labelNama.setBackground(new java.awt.Color(255, 255, 255));
        labelNama.setFont(new java.awt.Font("Poor Richard", 1, 22)); // NOI18N
        labelNama.setForeground(new java.awt.Color(80, 148, 101));
        labelNama.setText("Nama Surat");
        jPanel2.add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 120, 70));

        labelJudul.setBackground(new java.awt.Color(255, 255, 255));
        labelJudul.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        labelJudul.setForeground(new java.awt.Color(80, 148, 101));
        labelJudul.setText("Murottal 30 Juz");
        jPanel2.add(labelJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 130, 50));

        labelKategori.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        labelKategori.setText("Cari Surat");
        jPanel2.add(labelKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 260, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/1.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-176, 0, 830, 460));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 0, 650, 455));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setSuratList(DefaultListModel model) {
        jListCariSurat.setModel(model);
    }

    public String getTfNamaSurat() {
        return tfNamaSurat.getText();
    }
    
    public void resetView() {
        tfNamaSurat.setText("");
    }
    
    public JButton getBtnCari() {
        return btnCari;
    }
    
    public JButton getBtnBack() {
        return btnBack;
    }

    public JButton getBtnPlay() {
        return btnPlay;
    }
    
    public JList getList() {
        return jListCariSurat;
    }

    public int getIndexListTerpilih() {
        return jListCariSurat.getSelectedIndex();
    }
    
    public void addActionListener(ActionListener e) {
        btnCari.addActionListener(e);
        btnBack.addActionListener(e);
        btnPlay.addActionListener(e);
    }
    
    public void addMouseAdapter(MouseAdapter e) {
        jListCariSurat.addMouseListener(e);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListCariSurat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelKategori;
    private javax.swing.JLabel labelNama;
    private javax.swing.JScrollPane spJuz;
    private javax.swing.JTextField tfNamaSurat;
    // End of variables declaration//GEN-END:variables
}
