/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ChomeGUI;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.*;
import java.sql.*;
import java.awt.Dimension;
import javax.swing.JFrame;
import java.sql.ResultSet;
import java.sql.Statement;
/**
 *
 * @author MY PC
 */
public class HomeGUI extends javax.swing.JFrame {
    
    /**
     * Creates new form Home
     */
    public HomeGUI() {
        initComponents();
        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnKategori = new javax.swing.JButton();
        btnFaq = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        labelJudul = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnHome.setForeground(new java.awt.Color(80, 148, 101));
        btnHome.setText("Home");
        jPanel2.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 166, 55));

        btnKategori.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnKategori.setForeground(new java.awt.Color(80, 148, 101));
        btnKategori.setText("Kategori");
        jPanel2.add(btnKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 180, 55));

        btnFaq.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnFaq.setForeground(new java.awt.Color(80, 148, 101));
        btnFaq.setText("FAQ");
        jPanel2.add(btnFaq, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 166, 55));

        btnHelp.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnHelp.setForeground(new java.awt.Color(80, 148, 101));
        btnHelp.setText("Bantuan");
        jPanel2.add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 166, 55));

        btnAbout.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(80, 148, 101));
        btnAbout.setText("Tentang Kami");
        jPanel2.add(btnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 180, 55));

        labelJudul.setFont(new java.awt.Font("Vivaldi", 1, 56)); // NOI18N
        labelJudul.setText("Murottal 30 Juz");
        jPanel2.add(labelJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 400, 101));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/1.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-176, 0, 830, 460));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 0, 650, 455));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public JButton getBtnAbout() {
        return btnAbout;
    }

    public JButton getBtnFaq() {
        return btnFaq;
    }

    public JButton getBtnHelp() {
        return btnHelp;
    }

    public JButton getBtnHome() {
        return btnHome;
    }

    public JButton getBtnKategori() {
        return btnKategori;
    }
    
    public void addActionListener(ActionListener e) {
        btnAbout.addActionListener(e);
        btnFaq.addActionListener(e);
        btnHelp.addActionListener(e);
        btnHome.addActionListener(e);
        btnKategori.addActionListener(e);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnFaq;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnKategori;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelJudul;
    // End of variables declaration//GEN-END:variables
}
