/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CkategoriGUI;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.*;
import java.sql.*;
import java.awt.Dimension;
import javax.swing.JFrame;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author MY PC
 */
public class KategoriGUI extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public KategoriGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnBack = new javax.swing.JButton();
        labelJudul = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        btnMakiyyah = new javax.swing.JButton();
        btnMadaniyyah = new javax.swing.JButton();
        btnCariSurat = new javax.swing.JButton();
        btnAllSurat = new javax.swing.JButton();
        labelKategori = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 620, 20));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(80, 148, 101));
        btnBack.setText("Kembali");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 100, 40));

        labelJudul.setBackground(new java.awt.Color(255, 255, 255));
        labelJudul.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        labelJudul.setForeground(new java.awt.Color(80, 148, 101));
        labelJudul.setText("Murottal 30 Juz");
        jPanel2.add(labelJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 130, 50));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(1);
        jTextArea1.setFont(new java.awt.Font("Tw Cen MT", 1, 23)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(80, 148, 101));
        jTextArea1.setRows(5);
        jTextArea1.setText("“Apabila dibacakan al-Qur'an, perhatikanlah dan diamlah, \nmaka kalian akan mendapatkan rahmat.” (QS. al-A’raf: 204).");
        jTextArea1.setToolTipText("");
        jTextArea1.setOpaque(false);
        jPanel2.add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 590, 60));

        btnMakiyyah.setFont(new java.awt.Font("Tw Cen MT", 1, 19)); // NOI18N
        btnMakiyyah.setForeground(new java.awt.Color(80, 148, 101));
        btnMakiyyah.setText("Makiyyah");
        btnMakiyyah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakiyyahActionPerformed(evt);
            }
        });
        jPanel2.add(btnMakiyyah, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 140, 40));

        btnMadaniyyah.setFont(new java.awt.Font("Tw Cen MT", 1, 19)); // NOI18N
        btnMadaniyyah.setForeground(new java.awt.Color(80, 148, 101));
        btnMadaniyyah.setText("Madaniyyah");
        jPanel2.add(btnMadaniyyah, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 140, 40));

        btnCariSurat.setFont(new java.awt.Font("Tw Cen MT", 1, 19)); // NOI18N
        btnCariSurat.setForeground(new java.awt.Color(80, 148, 101));
        btnCariSurat.setText("Cari Surat");
        jPanel2.add(btnCariSurat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 140, 40));

        btnAllSurat.setFont(new java.awt.Font("Tw Cen MT", 1, 19)); // NOI18N
        btnAllSurat.setForeground(new java.awt.Color(80, 148, 101));
        btnAllSurat.setText("Semua Surat");
        jPanel2.add(btnAllSurat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 140, 40));

        labelKategori.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        labelKategori.setText("Kategori");
        jPanel2.add(labelKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 160, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/1.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-176, 0, 830, 460));
        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 0, 650, 455));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnMakiyyahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakiyyahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMakiyyahActionPerformed

    public JButton getBtnAllSurat() {
        return btnAllSurat;
    }

    public JButton getBtnBack() {
        return btnBack;
    }

    public JButton getBtnCariSurat() {
        return btnCariSurat;
    }

    public JButton getBtnMadaniyyah() {
        return btnMadaniyyah;
    }

    public JButton getBtnMakiyyah() {
        return btnMakiyyah;
    }

    public void addActionListener(ActionListener e) {
        btnAllSurat.addActionListener(e);
        btnBack.addActionListener(e);
        btnCariSurat.addActionListener(e);
        btnMadaniyyah.addActionListener(e);
        btnMakiyyah.addActionListener(e);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllSurat;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCariSurat;
    private javax.swing.JButton btnMadaniyyah;
    private javax.swing.JButton btnMakiyyah;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelKategori;
    // End of variables declaration//GEN-END:variables

}
